# Generated by Django 2.0.7 on 2018-08-19 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_comment_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
    ]
