# Generated by Django 2.0.7 on 2018-08-19 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_article_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='article',
            name='views',
        ),
    ]
