# Generated by Django 2.0.7 on 2018-08-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='county',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
