# Generated by Django 2.0.7 on 2018-08-05 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_game_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('console_type', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Brand'),
        ),
        migrations.AlterField(
            model_name='game',
            name='console',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Console'),
        ),
    ]
