# Generated by Django 2.0.7 on 2018-08-05 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180805_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='console',
            name='brand',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.Brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='console',
            name='image',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
